### ISSUE TITLE
Farsi text bugs

### ISSUE THREAD

**Issue by Strahfe** [codehub-ir/codehub#45]
When you create a new snippet, all Persian words bug and be shown reversed!

![image](https://user-images.githubusercontent.com/96849414/147711520-d7451a27-dfcb-4168-b77c-6d2b60ccf826.png)

**Comment by Strahfe** [comment]
I can work on it and fix it BTW. :)

**Comment by lnxpy** [comment]
Hi Arshia,
Thanks for considering. Let me know when you fixed it by creating a new PR and mentioning this issue as well.
